// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by hack/docgen tool. DO NOT EDIT.

package k8s

import (
	"github.com/siderolabs/talos/pkg/machinery/config/encoder"
)

func (KubeEtcdEncryptionConfigV1Alpha1) Doc() *encoder.Doc {
	doc := &encoder.Doc{
		Type:        "KubeEtcdEncryptionConfig",
		Comments:    [3]string{"" /* encoder.HeadComment */, "KubeEtcdEncryptionConfig configures kube-apiserver etcd encryption rules." /* encoder.LineComment */, "" /* encoder.FootComment */},
		Description: "KubeEtcdEncryptionConfig configures kube-apiserver etcd encryption rules.",
		Fields: []encoder.Doc{
			{
				Type:   "Meta",
				Inline: true,
			},
			{
				Name:        "config",
				Type:        "Unstructured",
				Note:        "",
				Description: "Kubernetes API server [encryption of secret data at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/).\nKey value should be exact contents of the configuration file, excluding the apiVersion and kind fields.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "Kubernetes API server [encryption of secret data at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/)." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
		},
	}

	doc.AddExample("", exampleKubeEtcdEncryptionConfigV1Alpha1())

	return doc
}

// GetFileDoc returns documentation for the file k8s_doc.go.
func GetFileDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "k8s",
		Description: "",
		Structs: []*encoder.Doc{
			KubeEtcdEncryptionConfigV1Alpha1{}.Doc(),
		},
	}
}
