// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: machine/md.proto

package machine

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MDCreateRequest provisions a new bootable RAID1 mirror.
type MDCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the array name to stamp into the metadata (e.g. "talos"). The
	// running system exposes it as /dev/disk/by-id/md-name-<name>.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Disks are the absolute paths of the whole disks to mirror
	// (e.g. ["/dev/sda", "/dev/sdb"]); at least two are required. Each is
	// partitioned (ESP + RAID member) - any existing data is wiped.
	Disks         []string `protobuf:"bytes,2,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDCreateRequest) Reset() {
	*x = MDCreateRequest{}
	mi := &file_machine_md_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDCreateRequest) ProtoMessage() {}

func (x *MDCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_md_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDCreateRequest.ProtoReflect.Descriptor instead.
func (*MDCreateRequest) Descriptor() ([]byte, []int) {
	return file_machine_md_proto_rawDescGZIP(), []int{0}
}

func (x *MDCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MDCreateRequest) GetDisks() []string {
	if x != nil {
		return x.Disks
	}
	return nil
}

// MDCreateResponse reports the provisioned mirror.
type MDCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device is the array block-device node (e.g. "/dev/md0"), the install target.
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// EspDevices are the per-disk EFI System Partition device paths, one per
	// member disk, in the same order as the request.
	EspDevices    []string `protobuf:"bytes,2,rep,name=esp_devices,json=espDevices,proto3" json:"esp_devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDCreateResponse) Reset() {
	*x = MDCreateResponse{}
	mi := &file_machine_md_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDCreateResponse) ProtoMessage() {}

func (x *MDCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_md_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDCreateResponse.ProtoReflect.Descriptor instead.
func (*MDCreateResponse) Descriptor() ([]byte, []int) {
	return file_machine_md_proto_rawDescGZIP(), []int{1}
}

func (x *MDCreateResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *MDCreateResponse) GetEspDevices() []string {
	if x != nil {
		return x.EspDevices
	}
	return nil
}

// MDExtendRequest adds members to an existing array.
type MDExtendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the array name (e.g. "md0").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Devices are the absolute block device paths to add as new members
	// (e.g. ["/dev/sdc"]); bare kernel names are not accepted.
	Devices       []string `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDExtendRequest) Reset() {
	*x = MDExtendRequest{}
	mi := &file_machine_md_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDExtendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDExtendRequest) ProtoMessage() {}

func (x *MDExtendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_md_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDExtendRequest.ProtoReflect.Descriptor instead.
func (*MDExtendRequest) Descriptor() ([]byte, []int) {
	return file_machine_md_proto_rawDescGZIP(), []int{2}
}

func (x *MDExtendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MDExtendRequest) GetDevices() []string {
	if x != nil {
		return x.Devices
	}
	return nil
}

// MDShrinkRequest removes members from an existing array.
type MDShrinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the array name (e.g. "md0").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Devices are the absolute block device paths of the members to remove
	// (e.g. ["/dev/sdc"]); bare kernel names are not accepted.
	Devices       []string `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDShrinkRequest) Reset() {
	*x = MDShrinkRequest{}
	mi := &file_machine_md_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDShrinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDShrinkRequest) ProtoMessage() {}

func (x *MDShrinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_md_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDShrinkRequest.ProtoReflect.Descriptor instead.
func (*MDShrinkRequest) Descriptor() ([]byte, []int) {
	return file_machine_md_proto_rawDescGZIP(), []int{3}
}

func (x *MDShrinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MDShrinkRequest) GetDevices() []string {
	if x != nil {
		return x.Devices
	}
	return nil
}

// MDDestroyRequest identifies the array to tear down.
type MDDestroyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the array name to destroy (e.g. "md0").
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDDestroyRequest) Reset() {
	*x = MDDestroyRequest{}
	mi := &file_machine_md_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDDestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDDestroyRequest) ProtoMessage() {}

func (x *MDDestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_md_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDDestroyRequest.ProtoReflect.Descriptor instead.
func (*MDDestroyRequest) Descriptor() ([]byte, []int) {
	return file_machine_md_proto_rawDescGZIP(), []int{4}
}

func (x *MDDestroyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_machine_md_proto protoreflect.FileDescriptor

const file_machine_md_proto_rawDesc = "" +
	"\n" +
	"\x10machine/md.proto\x12\amachine\x1a\x1bgoogle/protobuf/empty.proto\";\n" +
	"\x0fMDCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05disks\x18\x02 \x03(\tR\x05disks\"K\n" +
	"\x10MDCreateResponse\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1f\n" +
	"\vesp_devices\x18\x02 \x03(\tR\n" +
	"espDevices\"?\n" +
	"\x0fMDExtendRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adevices\x18\x02 \x03(\tR\adevices\"?\n" +
	"\x0fMDShrinkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adevices\x18\x02 \x03(\tR\adevices\"&\n" +
	"\x10MDDestroyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x80\x02\n" +
	"\tMDService\x12=\n" +
	"\x06Create\x12\x18.machine.MDCreateRequest\x1a\x19.machine.MDCreateResponse\x12:\n" +
	"\x06Extend\x12\x18.machine.MDExtendRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x06Shrink\x12\x18.machine.MDShrinkRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\aDestroy\x12\x19.machine.MDDestroyRequest\x1a\x16.google.protobuf.EmptyBN\n" +
	"\x15dev.talos.api.machineZ5github.com/siderolabs/talos/pkg/machinery/api/machineb\x06proto3"

var (
	file_machine_md_proto_rawDescOnce sync.Once
	file_machine_md_proto_rawDescData []byte
)

func file_machine_md_proto_rawDescGZIP() []byte {
	file_machine_md_proto_rawDescOnce.Do(func() {
		file_machine_md_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_machine_md_proto_rawDesc), len(file_machine_md_proto_rawDesc)))
	})
	return file_machine_md_proto_rawDescData
}

var file_machine_md_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_machine_md_proto_goTypes = []any{
	(*MDCreateRequest)(nil),  // 0: machine.MDCreateRequest
	(*MDCreateResponse)(nil), // 1: machine.MDCreateResponse
	(*MDExtendRequest)(nil),  // 2: machine.MDExtendRequest
	(*MDShrinkRequest)(nil),  // 3: machine.MDShrinkRequest
	(*MDDestroyRequest)(nil), // 4: machine.MDDestroyRequest
	(*emptypb.Empty)(nil),    // 5: google.protobuf.Empty
}
var file_machine_md_proto_depIdxs = []int32{
	0, // 0: machine.MDService.Create:input_type -> machine.MDCreateRequest
	2, // 1: machine.MDService.Extend:input_type -> machine.MDExtendRequest
	3, // 2: machine.MDService.Shrink:input_type -> machine.MDShrinkRequest
	4, // 3: machine.MDService.Destroy:input_type -> machine.MDDestroyRequest
	1, // 4: machine.MDService.Create:output_type -> machine.MDCreateResponse
	5, // 5: machine.MDService.Extend:output_type -> google.protobuf.Empty
	5, // 6: machine.MDService.Shrink:output_type -> google.protobuf.Empty
	5, // 7: machine.MDService.Destroy:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_machine_md_proto_init() }
func file_machine_md_proto_init() {
	if File_machine_md_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_machine_md_proto_rawDesc), len(file_machine_md_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_machine_md_proto_goTypes,
		DependencyIndexes: file_machine_md_proto_depIdxs,
		MessageInfos:      file_machine_md_proto_msgTypes,
	}.Build()
	File_machine_md_proto = out.File
	file_machine_md_proto_goTypes = nil
	file_machine_md_proto_depIdxs = nil
}
