// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: machine/md.proto

package machine

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MDService_Create_FullMethodName  = "/machine.MDService/Create"
	MDService_Extend_FullMethodName  = "/machine.MDService/Extend"
	MDService_Shrink_FullMethodName  = "/machine.MDService/Shrink"
	MDService_Destroy_FullMethodName = "/machine.MDService/Destroy"
)

// MDServiceClient is the client API for MDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MDService provisions and maintains MD (Multiple Device, software RAID)
// arrays. It is an administrator API, intended to be used in maintenance mode
// before installation to lay down a mirrored system disk.
//
//   - Create:  provision a bootable RAID1 mirror from whole disks.
//   - Extend:  add member devices (e.g. a replacement disk).
//   - Shrink:  remove member devices (e.g. a failed disk).
//   - Destroy: stop the array and clear member superblocks.
//
// Extend + Shrink together replace failed hardware: add the replacement
// member, let it resync, then remove the failed member.
type MDServiceClient interface {
	// Create provisions a bootable RAID1 mirror from the given whole disks.
	//
	// Each disk is partitioned into an EFI System Partition (kept outside the
	// array so UEFI can boot from either disk) plus a RAID-member partition; the
	// RAID1 array is created across the member partitions. The resulting array
	// is the install target (GPT-on-md for META/STATE/EPHEMERAL).
	Create(ctx context.Context, in *MDCreateRequest, opts ...grpc.CallOption) (*MDCreateResponse, error)
	// Extend adds member devices to an existing array.
	//
	// For RAID1 this increases the number of mirrors. To replace a failed
	// member, Extend with the new device first, wait for the resync to
	// finish, then Shrink the failed member out.
	Extend(ctx context.Context, in *MDExtendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Shrink removes member devices from an existing array.
	//
	// The removed member's superblock is cleared so the device can be
	// reused. Shrinking below the array's redundancy minimum is rejected.
	Shrink(ctx context.Context, in *MDShrinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Destroy stops the array and clears the superblock on every member.
	//
	// The array must not be in use (e.g. mounted or claimed by another
	// device) at the time of the call.
	Destroy(ctx context.Context, in *MDDestroyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMDServiceClient(cc grpc.ClientConnInterface) MDServiceClient {
	return &mDServiceClient{cc}
}

func (c *mDServiceClient) Create(ctx context.Context, in *MDCreateRequest, opts ...grpc.CallOption) (*MDCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MDCreateResponse)
	err := c.cc.Invoke(ctx, MDService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDServiceClient) Extend(ctx context.Context, in *MDExtendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MDService_Extend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDServiceClient) Shrink(ctx context.Context, in *MDShrinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MDService_Shrink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDServiceClient) Destroy(ctx context.Context, in *MDDestroyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MDService_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MDServiceServer is the server API for MDService service.
// All implementations must embed UnimplementedMDServiceServer
// for forward compatibility.
//
// MDService provisions and maintains MD (Multiple Device, software RAID)
// arrays. It is an administrator API, intended to be used in maintenance mode
// before installation to lay down a mirrored system disk.
//
//   - Create:  provision a bootable RAID1 mirror from whole disks.
//   - Extend:  add member devices (e.g. a replacement disk).
//   - Shrink:  remove member devices (e.g. a failed disk).
//   - Destroy: stop the array and clear member superblocks.
//
// Extend + Shrink together replace failed hardware: add the replacement
// member, let it resync, then remove the failed member.
type MDServiceServer interface {
	// Create provisions a bootable RAID1 mirror from the given whole disks.
	//
	// Each disk is partitioned into an EFI System Partition (kept outside the
	// array so UEFI can boot from either disk) plus a RAID-member partition; the
	// RAID1 array is created across the member partitions. The resulting array
	// is the install target (GPT-on-md for META/STATE/EPHEMERAL).
	Create(context.Context, *MDCreateRequest) (*MDCreateResponse, error)
	// Extend adds member devices to an existing array.
	//
	// For RAID1 this increases the number of mirrors. To replace a failed
	// member, Extend with the new device first, wait for the resync to
	// finish, then Shrink the failed member out.
	Extend(context.Context, *MDExtendRequest) (*emptypb.Empty, error)
	// Shrink removes member devices from an existing array.
	//
	// The removed member's superblock is cleared so the device can be
	// reused. Shrinking below the array's redundancy minimum is rejected.
	Shrink(context.Context, *MDShrinkRequest) (*emptypb.Empty, error)
	// Destroy stops the array and clears the superblock on every member.
	//
	// The array must not be in use (e.g. mounted or claimed by another
	// device) at the time of the call.
	Destroy(context.Context, *MDDestroyRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMDServiceServer()
}

// UnimplementedMDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMDServiceServer struct{}

func (UnimplementedMDServiceServer) Create(context.Context, *MDCreateRequest) (*MDCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedMDServiceServer) Extend(context.Context, *MDExtendRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Extend not implemented")
}
func (UnimplementedMDServiceServer) Shrink(context.Context, *MDShrinkRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shrink not implemented")
}
func (UnimplementedMDServiceServer) Destroy(context.Context, *MDDestroyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedMDServiceServer) mustEmbedUnimplementedMDServiceServer() {}
func (UnimplementedMDServiceServer) testEmbeddedByValue()                   {}

// UnsafeMDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MDServiceServer will
// result in compilation errors.
type UnsafeMDServiceServer interface {
	mustEmbedUnimplementedMDServiceServer()
}

func RegisterMDServiceServer(s grpc.ServiceRegistrar, srv MDServiceServer) {
	// If the following call panics, it indicates UnimplementedMDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MDService_ServiceDesc, srv)
}

func _MDService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MDCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDServiceServer).Create(ctx, req.(*MDCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDService_Extend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MDExtendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDServiceServer).Extend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDService_Extend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDServiceServer).Extend(ctx, req.(*MDExtendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDService_Shrink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MDShrinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDServiceServer).Shrink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDService_Shrink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDServiceServer).Shrink(ctx, req.(*MDShrinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDService_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MDDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDServiceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDService_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDServiceServer).Destroy(ctx, req.(*MDDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MDService_ServiceDesc is the grpc.ServiceDesc for MDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "machine.MDService",
	HandlerType: (*MDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MDService_Create_Handler,
		},
		{
			MethodName: "Extend",
			Handler:    _MDService_Extend_Handler,
		},
		{
			MethodName: "Shrink",
			Handler:    _MDService_Shrink_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _MDService_Destroy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "machine/md.proto",
}
